### ISSUE TITLE
Need new Configuration directory to contain bluemix.plist and info.plist

### ISSUE THREAD

**Issue by trishayy** [IBM-Swift/TodoList-iOS#7]
Currently, there is a bluemix.plist file and an info.plist file. Inside the Xcode project, it appears that these files are inside a Configuration directory. But if you view the project inside Finder, they are not _actually_ in that directory.

These files need to be in this directory in order for IBM Cloud Tools for Swift to be able to run TodoList. 

Also, inside Bluemix.plist isLocal needs to be changed to true.

I can make these changes myself and make a PR if someone would like to add me to the project.

Thanks

**Comment by rfdickerson** [comment]
Hi Trisha, I think you now have write-access to this repo. Feel free to make those necessary changes here if you want.

**Comment by trishayy** [comment]
Issued closed with PR#8
